Service:
  RegionId: ap-southeast-1
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: sp-
    SupplierDeployMetadata:
      UserType: Aliyun
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 'ros_templates/template.yaml'
          AllowedRegions:
            - ap-southeast-1
          PredefinedParameters:
            - Name: 低配版
              Description: 该套餐采用了2vCPU 4GB内存的ECS实例（ecs.c6.large），系统盘采用200G的cloud_essd，可以满足基本的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.large']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 基础版
              Description: 该套餐采用了4vCPU 8GB内存的ECS实例（ecs.c6.xlarge），系统盘采用200G的cloud_essd，该配置可以满足大部分的业务需求。
              Parameters:
                EcsInstanceType: ['ecs.c6.xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 高配版
              Description: 该套餐采用了8vCPU 16GB内存的ECS实例（ecs.c6.2xlarge），系统盘采用200G的cloud_essd，该配置使用了更高规格ECS，进一步提升了整体稳定性和性能。
              Parameters:
                EcsInstanceType: ['ecs.c6.2xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
          HiddenParameterKeys:
            - EcsInstanceType
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                ap-southeast-1:
                  Parameters:
                    VpcId: ${VpcId}
                    ZoneId: ${ZoneId}
                    VSwitchId: ${VSwitchId}
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    NetworkMetadata:
      EnablePrivateVpcConnection: false
  ServiceType: managed
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: 单机版
        Operation:
          - Name: 变配套餐
            Description: 变配套餐
            Type: Custom
            SupportPredefinedParameters: true
            EnableLogging: false
    StatusOperationConfigs:
      - TemplateName: 单机版
        DeployScene: ECS
        SupportOperations:
          - Start
          - Stop
          - Restart
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: springboot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot单机托管版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: SpringBootPackage
    Description: 这是一个使用SpringBoot的测试包
    ArtifactProperty:
      RegionId: ap-southeast-1
      Url: 'resources/artifact_resources/file/package.tgz'